import { DefaultTheme } from "styled-components";

export const COLORS = {
  WHITE: "#fff",
  PRINCIPAL_WHITE: "#fcd9b7",
  BLACK: "#000",
  LIGHT_BLACK: "#111111",
  TRANSPARENT_BLACK: "rgba(0, 0, 0, 0.8)",
  PRINCIPAL_GRAY: "#9199ad",
  GRAY_1: "#999",
  GRAY_2: "#555",
  GRAY_3: "#252525",
  GRAY_4: "#252525",
  GRAY_5: "#ccc",
  PRINCIPAL_BLUE: "#172639",
  LIGHT_PRINCIPAL_BLUE: "#385c8a",
  ORANGE: "#e4683a",
  DARK_ORANGE: "#ff5d20",
  LIGHT_ORANGE: "#ff7d4d",
  RED: "#dc4848",
};

export const PrimaryTheme: DefaultTheme = {
  colorPrimary: COLORS.PRINCIPAL_GRAY,
  colorLightPrimary: COLORS.LIGHT_ORANGE,
  colorDarkPrimary: COLORS.DARK_ORANGE,
  colorSecondary: COLORS.PRINCIPAL_BLUE,
  colorBackgroundPrimary: COLORS.BLACK,
  colorBackgroundSecondary: COLORS.GRAY_3,
  colorBackgroundTertiary: COLORS.TRANSPARENT_BLACK,
  colorBackgroundQuaternary: COLORS.LIGHT_BLACK,
  colorBackgroundModalHeader: COLORS.GRAY_4,
  colorDanger: COLORS.RED,
  textAccentColor: COLORS.PRINCIPAL_WHITE,
  textBodyColor: COLORS.GRAY_2,
  textPrimaryColor: COLORS.GRAY_2,
  textSecondaryColor: COLORS.GRAY_1,
  textTertiaryColor: COLORS.BLACK,
  anchorHoverColor: COLORS.LIGHT_PRINCIPAL_BLUE,
  inputTextColorPrimary: COLORS.GRAY_5,
  inputTextColorSecondary: COLORS.GRAY_2,
  inputBackgroundColor: COLORS.GRAY_4,
  inputBackgroundEnabledColor: COLORS.GRAY_2,
} as const;
