export const COLORS = {
  WHITE: "#fff",
  BLACK: "#000",
  LIGHT_BLACK: "#111111",
  TRANSPARENT_BLACK: "rgba(0, 0, 0, 0.8)",
  GRAY_1: "#999",
  GRAY_2: "#555",
  GRAY_3: "#333",
  GRAY_4: "#252525",
  GRAY_5: "#ccc",
  LIGHT_BLUE: "#009ba2",
  ORANGE: "#ff5d20",
  DARK_ORANGE: "#ff5d20",
  LIGHT_ORANGE: "#ff7845",
};

export const DEFAULT_THEME = {
  primary: COLORS.ORANGE,
  lightPrimary: COLORS.LIGHT_ORANGE,
  primary2: COLORS.DARK_ORANGE,
  background: COLORS.BLACK,
  background2: COLORS.GRAY_3,
  background3: COLORS.GRAY_4,
  background4: COLORS.TRANSPARENT_BLACK,
  background5: COLORS.LIGHT_BLACK,
  danger: COLORS.LIGHT_BLUE,
  text1: COLORS.WHITE,
  text2: COLORS.GRAY_1,
  text3: COLORS.BLACK,
  inputText: COLORS.GRAY_5,
  inputText2: COLORS.GRAY_2,
  inputBackground: COLORS.GRAY_4,
  disabledInputBackground: COLORS.GRAY_2,
};
