import { Permission } from "types/role.types";
import { ROLES } from "./role.constants";

export const PROFILE_PERMISSIONS = {
  CAN_EDIT_PROFILE: "CAN_EDIT_PROFILE",
};

export const DREAM_PERMISSIONS = {
  CAN_EDIT_DREAM: "CAN_EDIT_DREAM",
  CAN_DELETE_DREAM: "CAN_DELETE_DREAM",
};

export const PLAYLIST_PERMISSIONS = {
  CAN_EDIT_PLAYLIST: "CAN_EDIT_PLAYLIST",
  CAN_DELETE_PLAYLIST: "CAN_DELETE_PLAYLIST",
};

export const ADMIN_PERMISSIONS: Permission[] = [];

export const USER_PERMISSIONS: Permission[] = [
  PROFILE_PERMISSIONS.CAN_EDIT_PROFILE,
  DREAM_PERMISSIONS.CAN_EDIT_DREAM,
  DREAM_PERMISSIONS.CAN_DELETE_DREAM,
  PLAYLIST_PERMISSIONS.CAN_EDIT_PLAYLIST,
  PLAYLIST_PERMISSIONS.CAN_DELETE_PLAYLIST,
];

export const ROLE_PERMISSIONS = {
  [ROLES.ADMIN_GROUP]: ADMIN_PERMISSIONS,
  [ROLES.USER_GROUP]: USER_PERMISSIONS,
};
