import { Permission } from "@/types/role.types";
import { ROLES } from "./role.constants";

export const PROFILE_PERMISSIONS = {
  CAN_EDIT_PROFILE: "CAN_EDIT_PROFILE",
};

export const DREAM_PERMISSIONS = {
  CAN_VIEW_ORIGINAL_VIDEO_DREAM: "CAN_VIEW_ORIGINAL_VIDEO_DREAM",
  CAN_CREATE_DREAM: "CAN_CREATE_DREAM",
  CAN_EDIT_DREAM: "CAN_EDIT_DREAM",
  CAN_VIEW_ORIGINAL_OWNER: "CAN_VIEW_ORIGINAL_OWNER",
  CAN_PROCESS_DREAM: "CAN_PROCESS_DREAM",
  CAN_VIEW_FEATURE_RANK: "CAN_VIEW_FEATURE_RANK",
  CAN_EDIT_FEATURE_RANK: "CAN_EDIT_FEATURE_RANK",
  CAN_DELETE_DREAM: "CAN_DELETE_DREAM",
};

export const PLAYLIST_PERMISSIONS = {
  CAN_EDIT_PLAYLIST: "CAN_EDIT_PLAYLIST",
  CAN_VIEW_FEATURE_RANK: "CAN_VIEW_FEATURE_RANK",
  CAN_VIEW_ORIGINAL_OWNER: "CAN_VIEW_ORIGINAL_OWNER",
  CAN_EDIT_OWNER: "CAN_EDIT_OWNER",
  CAN_DELETE_PLAYLIST: "CAN_DELETE_PLAYLIST",
};

export const ADMIN_PERMISSIONS: Permission[] = [
  PROFILE_PERMISSIONS.CAN_EDIT_PROFILE,
  DREAM_PERMISSIONS.CAN_CREATE_DREAM,
  DREAM_PERMISSIONS.CAN_VIEW_ORIGINAL_VIDEO_DREAM,
  DREAM_PERMISSIONS.CAN_PROCESS_DREAM,
  DREAM_PERMISSIONS.CAN_VIEW_FEATURE_RANK,
  DREAM_PERMISSIONS.CAN_EDIT_FEATURE_RANK,
  DREAM_PERMISSIONS.CAN_VIEW_ORIGINAL_OWNER,
  DREAM_PERMISSIONS.CAN_EDIT_DREAM,
  DREAM_PERMISSIONS.CAN_DELETE_DREAM,
  PLAYLIST_PERMISSIONS.CAN_EDIT_PLAYLIST,
  PLAYLIST_PERMISSIONS.CAN_VIEW_FEATURE_RANK,
  PLAYLIST_PERMISSIONS.CAN_VIEW_ORIGINAL_OWNER,
  PLAYLIST_PERMISSIONS.CAN_EDIT_OWNER,
  PLAYLIST_PERMISSIONS.CAN_DELETE_PLAYLIST,
];

export const CREATOR_PERMISSIONS: Permission[] = [
  DREAM_PERMISSIONS.CAN_CREATE_DREAM,
];

export const USER_PERMISSIONS: Permission[] = [];

export const ROLE_PERMISSIONS = {
  [ROLES.ADMIN_GROUP]: ADMIN_PERMISSIONS,
  [ROLES.USER_GROUP]: USER_PERMISSIONS,
  [ROLES.CREATOR_GROUP]: CREATOR_PERMISSIONS,
};
