export const ROUTES = {
  ROOT: "/",
  LOGIN: "/login",
  SIGNUP: "/signup",
  CONFIRM_FORGOT_PASSWORD: "/confirm-forgot-password",
  CREATE: "/create",
  VIEW_DREAM: "/dream",
  MY_DREAMS: "/my-dreams",
  FEED: "/feed",
  PLAYLISTS: "/playlists",
  VIEW_PLAYLIST: "/playlist",
  PROFILE: "/profile",
  MY_PROFILE: "/my-profile",
  HELP: "/help",
  LEARN_MORE: "/learn-more",
  ABOUT: "/about",
  INSTALL: "/install",
  TERMS_OF_SERVICE: "/tos",
};
